### ISSUE TITLE
Explore possibility of MinGW Support

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#126]
It seems that v8 has some not-officially-supported-but-documented upstream support for mingw32 now.

https://code.google.com/p/v8/wiki/BuildingWithGYP#MinGW

This needs to be checked in order to provide Windows support

**Comment by ignisf** [comment]
cc @stormbreakerbg

**Comment by ignisf** [comment]
Some more info here: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-v8/PKGBUILD

**Comment by jarredholman** [comment]
I pretty much have this working now https://github.com/jarredholman/libv8/tree/mingw

I'm not sure what the process for pull request/reviews is here... there is both master and trunk, and I had to include some other changes because master was broken thanks to the "rc1" in the version.

**Comment by ignisf** [comment]
That looks great!
Can you open up a PR for each branch?

**Comment by jarredholman** [comment]
So what is trunk for? A somewhat never version of v8 (but still quite outdated?)?

**Comment by ignisf** [comment]
Whenever therubyracer gets ported to compile against the trunk version of libv8, I'll replace the current master branch with this trunk and will try to keep it up to date.

Unfortunately an effort to update therubyracer has started only recently and I haven't been keeping the trunk branch up to date.

**Comment by jarredholman** [comment]
trunk is going to be more difficult since icu is a dependency there. This might take a bit longer.

**Comment by ignisf** [comment]
I thought I explicitly disabled ICU with this line https://github.com/cowboyd/libv8/blob/trunk/ext/libv8/builder.rb#L34

**Comment by ignisf** [comment]
Resolved by #166

**Comment by jarredholman** [comment]
I'm still working on this for trunk as well. Somehow it is much more difficult.

**Comment by ignisf** [comment]
@jarredholman, trunk-rebase contains the trunk branch rebased on the changes in master. What seems to be the hold up? ICU?

**Comment by jarredholman** [comment]
Got past the ICU issue, but then ran into problems during the compile. Slowly getting there as I fix each issue.

So far I have had to add -std=c++11 to the compile flags (not sure how the Linux version builds without it) and fixed the order of includes in one of the source file.

Its currently stuck trying to build the "host" version of the tool because it apparently ignores the target cxxflags you provide. I should probably just get the ia32 version working first...

**Comment by ignisf** [comment]
If you think that this issue has been fixed in newer versions of v8, we should update and not waste time on it
