### ISSUE TITLE
Yosemite 10.10 and Xcode 6 - Incompatibility

### ISSUE THREAD

**Issue by edolyne** [cowboyd/libv8#131]
I have the Yosemite 10.10 and Xcode 6 beta's installed and I am running into an issue trying to install libv8.  The error message I am getting is:

➜  ~  gem install libv8
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
    ERROR: Failed to build gem native extension.

```
/Users/edolyne/.rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb
```

creating Makefile
Compiling v8 for x64
Using python 2.7.6
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Unable to find a compiler officially supported by v8.
It is recommended to use GCC v4.4 or higher
Using compiler: g++
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Unable to find a compiler officially supported by v8.
It is recommended to use GCC v4.4 or higher
../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
                 ^
1 error generated.
make[1]: **\* [/Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o] Error 1
make: **\* [x64.release] Error 2
/Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
    from /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/ext/libv8/location.rb:35:in`each'
    from /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/ext/libv8/location.rb:35:in `verify_installation!'
    from /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/ext/libv8/location.rb:26:in`install!'
    from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
    build/gyp/gyp --generator-output="out" build/all.gyp \
                  -Ibuild/standalone.gypi --depth=. \
                  -Dv8_target_arch=x64 \
                  -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
  CXX(target) /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o

extconf failed, exit code 1

Gem files will remain installed in /Users/edolyne/.rvm/gems/ruby-2.1.2/gems/libv8-3.16.14.3 for inspection.
Results logged to /Users/edolyne/.rvm/gems/ruby-2.1.2/extensions/x86_64-darwin-14/2.1.0/libv8-3.16.14.3/gem_make.out

And when checking gcc I get this message:

➜  ~  gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.34.4) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

I have tried a number of "fixes" on stack exchange and such without any resolution yet so I am hoping that someone may be able to help me here.

**Comment by dankozlowski** [comment]
I'm encountering this issue with OSX 10.10 and latest Ruby 2.1.2.  Do we have a solution?

**Comment by ignisf** [comment]
@dankozlowski yes -- this issue was fixed by https://github.com/cowboyd/libv8/pull/124
