### ISSUE TITLE
error compiling on el7

### ISSUE THREAD

**Issue by cristi1979** [cowboyd/libv8#163]
Anybody knows why I get this error when trying to compile the module?

    Compiling /home/gitlab_ce/rpmbuild/BUILDROOT/rubygem-libv8-3.16.14.7-1.el7.x86_64/usr/share/gems/gems/libv8-3.16.14.7/vendor/v8/src/macros.py ...
      File "/usr/share/gems/gems/libv8-3.16.14.7/vendor/v8/src/macros.py", line 31
        const NONE        = 0;
                 ^
    SyntaxError: invalid syntax
    
    error: Bad exit status from /var/tmp/rpm-tmp.cqwhnV (%install)

**Comment by ignisf** [comment]
Hello @cristi1979, did you manage to create your rpm? Looks like an error Python 3 would churn out when used to compile libv8

**Comment by ignisf** [comment]
Feel free to reopen this if you are still experiencing the issue
