### ISSUE TITLE
bundle install fails with Yosemite, rvm and ruby 2.1.x

### ISSUE THREAD

**Issue by shyam-habarakada** [cowboyd/libv8#169]
I was able to go back to `3.16.14.3` and workaround the issue, but bundle install is failing with the following error. Let me know if you need additional information. We have been able to reproduce the issue on several computers and first noticed it while setting up a brand new MacBook we purchased recently. 

As per the paths below, we user `.ruby-version` files to specify which rvm and gemsets to use.

```sh
$ gem install libv8 -v 3.16.14.7
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    /Users/shyam/.rvm/rubies/ruby-2.1.1/bin/ruby -r ./siteconf20150421-49239-1kmmjl.rb extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.6
Using compiler: /usr/bin/c++ (clang version 6.1.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from ../src/v8.h:60:
In file included from ../src/objects-inl.h:38:
In file included from ../src/elements.h:33:
In file included from ../src/heap.h:35:
In file included from ../src/incremental-marking.h:33:
In file included from ../src/mark-compact.h:32:
../src/spaces.h:896:26: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  bool exists() { return this != NULL && code_range_ != NULL; }
                         ^~~~    ~~~~
../src/spaces.h:898:9: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Werror,-Wtautological-undefined-compare]
    if (this == NULL || code_range_ == NULL) return false;
        ^~~~    ~~~~
2 errors generated.
make[1]: *** [/Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o] Error 1
make: *** [x64.release] Error 2
/Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/ext/libv8/location.rb:35:in `each'
	from /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/ext/libv8/location.rb:35:in `verify_installation!'
	from /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/diy-fp.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/dtoa.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fast-dtoa.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fixed-dtoa.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/once.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparse-data.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser-api.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/scanner.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/strtod.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/token.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/unicode.o
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/utils.o
  LIBTOOL-STATIC /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/libpreparser_lib.a
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser/preparser/preparser-process.o
  LINK(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/preparser
  CXX(target) /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o

extconf failed, exit code 1

Gem files will remain installed in /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/gems/libv8-3.16.14.7 for inspection.
Results logged to /Users/shyam/.rvm/gems/ruby-2.1.1@benchpress-server-rails-3-1/extensions/x86_64-darwin-12/2.1.0-static/libv8-3.16.14.7/gem_make.out
```

**Comment by shyam-habarakada** [comment]
Additional information—it did not fail with ruby 1.9.x (I was testing with 1.9.3.-p125)

**Comment by ignisf** [comment]
Can you paste the output of `ruby -e 'puts Gem::Platform.local.inspect'` on both 1.9 and 2.1?

**Comment by shyam-habarakada** [comment]
Here you go

```bash
$ ruby -e 'puts Gem::Platform.local.inspect'
#<Gem::Platform:0x80914bac @cpu="x86_64", @os="darwin", @version="12">
$ rvm use 1.9.3-p125
Using /Users/shyam/.rvm/gems/ruby-1.9.3-p125
$ ruby -e 'puts Gem::Platform.local.inspect'
#<Gem::Platform:0x80c36510 @cpu="x86_64", @os="darwin", @version="14">
```

**Comment by ignisf** [comment]
Ok, so we've seen this issue before. Ruby 2.1.1 on your system has been compiled two OS X versions before Yosemite. If you recompile it now, rubygems will correctly identify the darwin14 binary of libv8 and will pull it instead of compiling libv8.

Apart from that, I wonder why is `-Werror` switched on when two versions back I explicitly switched it off in order to prevent such failures with untested compilers.

**Comment by shyam-habarakada** [comment]
@ignisf not 100% sure what you mean. Just in case, I tried with ruby 2.1.2 (and before and after re-installign that ruby via rvm) and it still fails with the same error. Here is the platform inspect with ruby 2.1.2

    $ ruby -e 'puts Gem::Platform.local.inspect'
    #<Gem::Platform:0x3ff81943a098 @cpu="x86_64", @os="darwin", @version="13">

**Comment by ignisf** [comment]
Rubygems finds binary versions of the gem based on the local platform, which in your case is:

`x86_64-darwin-12` for Ruby 2.1.1

`x86_64-darwin-13` for Ruby 2.1.2

`x86_64-darwin-14` for Ruby 1.9.3

Or it falls back to the source version (which fails to compile in your environment). Currently we have the following versions of libv8 pushed to rubygems:

![image](https://cloud.githubusercontent.com/assets/1153188/7295875/d9ecdb70-e9c2-11e4-9500-3bc1286a177c.png)

Having said that, I have no idea why rubygems doesn't pull the darwin-13 binary in your Ruby 2.1.2 environment.

**Comment by cowboyd** [comment]
And if you re-compiled it, why is it reporting darwin-13 instead of darwin-14? Very odd indeed. Is rvm installing a binary or compiling from source?

**Comment by shartep** [comment]
try
gem install libv8 -- --with-system-v8

**Comment by JEG2** [comment]
If you are on the darwin-14 platform, just fetch and install the binary gem:

```
gem fetch libv8 -v 3.16.14.7 --platform x86_64-darwin-14
gem install libv8-3.16.14.7-x86_64-darwin-14.gem
gem install therubyracer
```

**Comment by anolson** [comment]
I am having the same exact issue that @shyam-habarakada described.  I found that if I downgraded the OS X Command Line Tools from 6.3.1 to 6.2, I was able to successfully compile libv8.

**Comment by osca** [comment]
What i did was to use another ruby version (using rvm):
```
rvm install ruby-2.1-head
rvm use ruby-2.1-head
bundle install
```
Installed excejs, libv8 and therubyracer without any problems and I still have the latest xcode (command line tools) installed.
Hope this helps.

**Comment by sagarjunnarkar** [comment]
@shyam-habarakada thanks man. My OSX version is 10.10.1 (14B25). I tried this
```$ ruby -e 'puts Gem::Platform.local.inspect'``` and version is 13
```rvm get stable``` then ```rvm remove ruby  ruby-1.9.3-p484``` then ```rvm install ruby-1.9.3-p484```
Now ```$ ruby -e 'puts Gem::Platform.local.inspect'``` and version is 14
And ```bundle install``` Hurreey!!!

**Comment by vanetten** [comment]
Wow.. this was a pain.

My ruby had the wrong version too.

ruby -e 'puts Gem::Platform.local.inspect'
#<Gem::Platform:0x80c8cbe0 @cpu="x86_64", @os="darwin", @version="12">

Had to remove the ruby and re-install from source to get it right.
rvm install 2.1.1 --disable-binary

ruby -e 'puts Gem::Platform.local.inspect'
#<Gem::Platform:0x3ff39a055cd0 @cpu="x86_64", @os="darwin", @version="14">

**Comment by noahgibbs** [comment]
I'm using a fresh RVM-installed binary of Ruby 2.2.1 and I show version 14 when I use the above, but I'm still getting this error.

I'm using Mac OS 10.10.3 as well.

**Comment by noahgibbs** [comment]
This still happens for me with a fresh Ruby 2.2.1 compiled locally (not from source) via RVM.

**Comment by noahgibbs** [comment]
But it succeeded on that ruby when installing --with-system-v8, which didn't work before. Okay, I can use it now. Thanks!

**Comment by shartep-elephant** [comment]
this help me:
- reinstall openssl http://mac-dev-env.patrickbougie.com/openssl/
- download ruby-2.1.1 from ftp://ftp.ruby-lang.org/pub/ruby/2.1/ruby-2.1.1.tar.gz
- unpack it
- in console go to dir ruby-2.1.1
- ./configure --prefix=/Users/devy/.rvm/rubies/ruby-2.1.1 --with-openssl-dir=/usr/local/openssl
#where devy is my username
- sudo make
- sudo make install
- go to project directory and check ruby version, type ruby -v
- see: ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin14.0]
- gem install bundle
- bundle

**Comment by tsechingho** [comment]
I got this issue too, my solution is following.

```
$ rvm remove 2.1.1
$ rvm cleanup all
$ rvm install 2.1.1 --disable-binary
$ gem install bundler -v 1.8.5
$ ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin14.0]
$ gem --version
2.4.8
$ ruby -e 'puts Gem::Platform.new(RUBY_PLATFORM)'
x86_64-darwin-14
$ gem install libv8 -v '3.16.14.7'
$ gem install therubyracer -v '0.12.1'
```

If you use rvm, please reinstall ruby after update Mac OS X and check your ruby platform too.
If there are binary builds of libv8, like `libv8-3.16.14.7-x86_64-darwin-14.gem`, you should work well.

**Comment by htatche** [comment]
@tsechingho I can't thank you enough, I've been messing around with this for almost 2 days. THANKS

**Comment by straggler7** [comment]
@tsechingho Thank you very much. Saved my day.

**Comment by justin808** [comment]
FWIW, I could not do anything to get Ruby 2.1.4 to work with the Ruby Racer Gem. Ruby 2.1.5 works fine.
