### ISSUE TITLE
add vagrant build for ARM

### ISSUE THREAD

**Issue by cowboyd** [cowboyd/libv8#188]

**Comment by ignisf** [comment]
It seems that there is a libvirt provider for Vagrant.

https://github.com/vagrant-libvirt/vagrant-libvirt

and specifically issue 589 from the issue tracker of the project.

**Comment by ignisf** [comment]
Having an issue installing vagrant-libvirt, see https://github.com/vagrant-libvirt/vagrant-libvirt/issues/497

**Comment by ignisf** [comment]
Opened upstream Vagrant issue: https://github.com/mitchellh/vagrant/issues/7330

**Comment by ignisf** [comment]
A workaround for Arch Linux exists: https://wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt

> This plugin adds a libvirt provider to Vagrant. The gcc and make packages must be installed before this plugin can be installed, and libvirt and related packages must be installed and configured before using the libvirt provider.
>
> At the time of writing (using Vagrant version 1.8.1), a normal installation of this plugin fails on Arch Linux. The plugin can be successfully installed with this workaround:
>
>     $ CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' \
>       GEM_HOME=~/.vagrant.d/gems GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH \
>       vagrant plugin install vagrant-libvirt
>
> Once the plugin is installed the libvirt provider will be available:
>
>     $ vagrant up --provider=libvirt

**Comment by ignisf** [comment]
I made an attempt to do this. Unfortunately it takes so long to compile a binary that it's easier to just use a C1 instance on Scaleway.
