### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by toncid** [cowboyd/libv8#189]
Any chance of adding a changelog to the repo?

Right now it is unclear what changed between 3.16 and 4.5. 

Thanks!

**Comment by saizai** [comment]
+1. Was just going to suggest.

**Comment by jk779** [comment]
so, what _did_ change?

**Comment by ignisf** [comment]
IIRC the binary gems for 3.16.14.8 were compiled with a GCC newer than 4.8 which was causing SEGFAULTs on many systems. So @cowboyd [fixed the version of GCC](https://github.com/cowboyd/libv8/commit/dc25d944a2e3fe91f5e58153f8a713e3dd520a81) and rereleased the binary gems.

More info on the versioning convention can be found here: https://github.com/cowboyd/libv8#versioning

**Comment by sockmonk** [comment]
While that's good to know, it would still be nice to have a CHANGELOG. Even if it only contains the versioning policy. :-)
