### ISSUE TITLE
The python version check uses incorrect syntax that errors on windows

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#194]
As reported here https://github.com/cowboyd/libv8/issues/29#issuecomment-125847914 by @badbob

**Comment by marcomd** [comment]
The syntax is correct now, it uses double quotes.

The error is another

"patch" is not recognized as an internal or external command

C:/ruby/ruby-223x64p173/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.13/ext/libv8/patcher.rb:51:in `block (2 levels) in patch!': failed to apply patch (RuntimeError)

**Comment by mnuzzolilo** [comment]
When will this be released?
