### ISSUE TITLE
Submodule `vendor/v8` commit no longer exists

### ISSUE THREAD

**Issue by vemek** [cowboyd/libv8#196]
It seems that the submodule commit pointed to for `vendor/v8` no longer exists. This causes bundler to fail installing libv8 using master, which I need to do due to the recent build patches for OS X 10.11.

```
~/src/libv8 [master|✔] git show
commit cf1f9a903e5961829712facf63fcabb60dcdadb9
Merge: 9188ace af738ac
Author: Charles Lowell <cowboyd@cogentdude.com>
Date:   Mon Jul 6 13:48:18 2015 -0500

    Merge pull request #177 from semnil/patch-for-clang-70

    add a patch for clang 7.0
~/src/libv8 [master|✔] git submodule update --init
Submodule 'vendor/gyp' (https://chromium.googlesource.com/external/gyp.git) registered for path 'vendor/gyp'
Submodule 'vendor/v8' (https://github.com/v8/v8.git) registered for path 'vendor/v8'
Submodule path 'vendor/gyp': checked out 'f7bc250ccc4d619a1cf238db87e5979f89ff36d7'
fatal: reference is not a tree: 7ce3fe106a37826dc23189a78dcb9000a1b3fa06
Unable to checkout '7ce3fe106a37826dc23189a78dcb9000a1b3fa06' in submodule path 'vendor/v8'
~/src/libv8/vendor [master|✚ 1] cd vendor/v8/
~/src/libv8/vendor/v8 [:2f0efde|●1913] git show 7ce3fe106a37826dc23189a78dcb9000a1b3fa06
fatal: bad object 7ce3fe106a37826dc23189a78dcb9000a1b3fa06
```

I'd like to PR a change to point the submodule at the correct v8 tag, but I'm not sure which patch of V3.16.14 you were targeting.

**Comment by ignisf** [comment]
IIRC it was pointed to the commit tagged with 3.16.14.

https://chromium.googlesource.com/v8/v8.git/+/2f0efdebb142c00de6950453b4c2df20ceb8df6e
https://github.com/v8/v8/commit/2f0efdebb142c00de6950453b4c2df20ceb8df6e

**Comment by vemek** [comment]
Cool, thanks - I've opened a quick PR here: https://github.com/cowboyd/libv8/pull/197
