### ISSUE TITLE
Can't install on Alpine Linux

### ISSUE THREAD

**Issue by reiz** [cowboyd/libv8#198]
I'm trying to install this on Aline Linux through a Ruby project. I have this line in my Gemfline: 

```
gem "libv8" , git: "git://github.com/cowboyd/libv8.git", submodules: true
```

But bundle install fails with this error message: 

```
No manual entry for git-svn
/usr/lib/ruby/gems/2.2.0/bundler/gems/libv8-78ee2548a0b1/ext/libv8/checkout.rb:48:in `check_git_svn!': git-svn not installed! (RuntimeError)
Please install git-svn.
	from /usr/lib/ruby/gems/2.2.0/bundler/gems/libv8-78ee2548a0b1/ext/libv8/checkout.rb:24:in `checkout!'
	from /usr/lib/ruby/gems/2.2.0/bundler/gems/libv8-78ee2548a0b1/ext/libv8/builder.rb:54:in `block in build_libv8!'
	from /usr/lib/ruby/gems/2.2.0/bundler/gems/libv8-78ee2548a0b1/ext/libv8/builder.rb:52:in `chdir'
	from /usr/lib/ruby/gems/2.2.0/bundler/gems/libv8-78ee2548a0b1/ext/libv8/builder.rb:52:in `build_libv8!'
	from /usr/lib/ruby/gems/2.2.0/bundler/gems/libv8-78ee2548a0b1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1
```

`git-svn` is installed! That for sure. But why does the installation fail because the man page for git-svn is missing? That is very frustrating :-(

**Comment by ignisf** [comment]
Can you test https://github.com/cowboyd/libv8/tree/git-svn-check please?

```
gem "libv8" , git: "git://github.com/cowboyd/libv8.git", branch: "git-svn-check". submodules: true
```

**Comment by reiz** [comment]
It's obsolete for right now. I decided to go ahead with Ubuntu as Docker base image because I had some odd character encoding issues with the combination Ruby + Alpine Linux. After one day debugging I couldn't resolve the encoding issues even by setting all kind of ENV variables to UTF-8. 
Libv8 works fine on Ubuntu!
