### ISSUE TITLE
Install fail OSX 10.9.4 with Ruby 2.1.2 under rbenv 1.0.0

### ISSUE THREAD

**Issue by lacostenycoder** [cowboyd/libv8#202]
Error log was so long I didn't want to post it here, instead gist

https://gist.github.com/lacostenycoder/70491398626104a87c6a

**Comment by ignisf** [comment]
Hello @lacostenycoder could you try again with libv8 5.0?

**Comment by ignisf** [comment]
Reopen if you have more information
