### ISSUE TITLE
Time for a new libv8 release :)

### ISSUE THREAD

**Issue by SamSaffron** [cowboyd/libv8#218]
https://omahaproxy.appspot.com/ 

Chrome 51 is out, so we should update to 5.1.281.59

**Comment by ignisf** [comment]
prerelase up for testing

**Comment by ignisf** [comment]
There's at least one important (and log awaited) change https://chromium.googlesource.com/v8/v8/+/e8c914f18fd88cd58aaaf5d8cee53b9e57477b52.

It will require a patch to mini_racer, will create a PR once I test it.

**Comment by ignisf** [comment]
https://github.com/cowboyd/libv8/commit/d7c013d88e2c7ee6a683a9a7eaa9953edfc885ac
