### ISSUE TITLE
libv8 5.1.281.59.1 affected by upstream issue 604033

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#219]
```ruby
require 'mini_racer'
ctx = MiniRacer::Context.new

ctx.eval "
function test() {
    var count = {true: 0, false: 0};
    var array = Array.apply(null, Array(10000)).map(function() { return(typeof(null) != 'undefined'); });
    array.forEach(function(value) { count[value] += 1; });
    return(count);
}
"
ctx.eval("test();")

#=> {"true"=>132, "false"=>9868}
```

https://bugs.chromium.org/p/chromium/issues/detail?id=604033

https://codereview.chromium.org/2088783002

https://www.reddit.com/r/javascript/comments/4oxtgk/javascript_developers_be_warned_about_this_crazy/

**Comment by ignisf** [comment]
@wk8, @samsaffron, shall I release a version based on 5.1.281.67?

**Comment by wk8** [comment]
@ignisf : I'm certainly all for it, that would be very much appreciated :)

**Comment by SamSaffron** [comment]
Sure, go for it :)

**Comment by ignisf** [comment]
Fixed in https://github.com/cowboyd/libv8/commit/082d90681c7ff349feaabd875b280ff92ccddf96
