### ISSUE TITLE
macOS Sierra platform-specific version of the gem

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#225]
Currently we produce platform-specific versions of the gem by building them on Travis. Until Travis rolls out macOS Sierra support, we have no way of producing binaries.

**Comment by ignisf** [comment]
Also, from Travis' docs:

> At this time we are unable to provide pre-release versions of Xcode due to the NDA imposed on them. We do test them internally, and our goal is to make new versions available the same day they come out. If you have any further questions about Xcode pre-release availability, send us an email at support@travis-ci.com.

**Comment by aviat** [comment]
@ignisf what about manually packaging a libv8 for macOS Sierra (10.12) from a 10.11 build? I expect no retro compatibility issue. If that works for you, I can provide you with the script to do it, and perform the testing myself as well.
The libv8 trust model won't be broken since it will remain between TravisCI (which builds for 10.11) and you.

**Comment by ignisf** [comment]
Sure, why not, if you can test it :)

**Comment by jk779** [comment]
Any news on this? Sierra is going to launch tomorrow and there is no binary version of libv8 yet. This is going to be a pain for a lot of people i think 🙅

**Comment by ignisf** [comment]
No, at least for now the plan still is for me to cut a release as soon as the nice people from Travis roll out Sierra build images.

> It seems that `3.16.14.15` and `5.3.332.38.1` are compiling without problems, though.

This is great news!

**Comment by ignisf** [comment]
Actually... There is news -- https://blog.travis-ci.com/2016-09-15-new-default-osx-image-coming/

**Comment by ignisf** [comment]
Another update from Travis: https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/

> osx_image: xcode8 (currently 10.11, but tentatively planned to be 10.12 once we've done some vSphere compatibility testing)

**Comment by mouse-lin** [comment]
macOS Sierra 10.12.1.
When i run command  ```gem install libv8 -v '5.3.332.38.1' ```. 
Package is corrupt exception: undefined method `size' for nil:NilClass (NoMethodError)
