### ISSUE TITLE
V8 5.4.500.31 requires binutils 2.26

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#227]
It seems that V8 now requires binutils 2.26 to build. The result of this is that one cannot build it on Ubuntu 14.04 (and anything under 16.04 really).

Error message:

```
/usr/bin/ld.gold: error: /home/travis/build/cowboyd/libv8/vendor/v8/out/x64.release/obj.target/mkpeephole/src/interpreter/bytecodes.o: unsupported reloc 42 against global symbol v8::internal::interpreter::BytecodeTraits<(v8::internal::interpreter::AccumulatorUse)2, (v8::internal::interpreter::OperandType)4>::GetOperandTypes()::operand_types
```

Full error log: https://travis-ci.org/cowboyd/libv8/jobs/167891871

Possible courses of action:
- Document the dependency on binutils >= 2.26 and go ahead without further actions. Pros: easy for maintaining. Cons: possibly an avalanche of unhappy users.
- Check the version of binutils on build time and decide between using the system version or the Google-provided binary version. Pros: easy for implementation. Cons: depending on a binary provided by a third party.
- Find and patch whatever imposes a dependency on reloc 42. Pros: cleanest solution. Cons: hard.

@samsaffron, thoughts?

**Comment by SamSaffron** [comment]
I think documenting should be fine, the reality is that very very very few
people go about compiling libv8

**Comment by seanmakesgames** [comment]
Here is one vote for 'customer that is fine with documentation route'

**Comment by ignisf** [comment]
Hey, unfortunately this bugs Alpine linux builds... :( Have to think of something better

**Comment by ignisf** [comment]
HA! I think I've cracked it!!! https://github.com/cowboyd/libv8/commit/a79d642a3bef972eefd3f4d961cd78e8608ae80b

**Comment by ignisf** [comment]
Seems that the build system falls back to the sysroot it downloads instead of using the system binutils......

**Comment by ignisf** [comment]
Fixed by https://github.com/cowboyd/libv8/commit/bb06abe6d71240da00c8c8a3b542f39049a8647f
