### ISSUE TITLE
GYP has been deprecated in favor of GN

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#228]
https://github.com/v8/v8/wiki/Building%20with%20Gyp

https://github.com/v8/v8/wiki/Building%20with%20GN
- [x] Find a way to produce a standalone archive instead of a thin one. Keywords in the ninja build files: `standalone_static_library`, `alink` and `alink_thin`.
- [x] Find a way to produce an `-fPIC` library (it could be possible to specify additional flags via a ninja build flag)
- [x] Skip building the test suite (it could be possible to give ninja a specific target to build)
- [ ] Use the system toolchain instead of the built-in ones (see ninja argument)
- [ ] Use the system binutils
- [ ] Use the system ld

**Comment by ignisf** [comment]
```
linux_use_bundled_binutils=false
clang_base_path=""
target_sysroot_dir=""
v8_use_external_startup_data=false
is_component_build=false
v8_monolithic=true
v8_enable_i18n_support=false
#use_xcode_clang=true
use_sysroot=false
use_pic=true
use_custom_libcxx=false
```

**Comment by SamSaffron** [comment]
Given 6.6 is now out and stable and GYP is gone, I am reaching out on Twitter to see if anyone can help us out here!

**Comment by ignisf** [comment]
Tracking issue for the system toolchain support: https://github.com/cowboyd/libv8/issues/260
