### ISSUE TITLE
Add architecture detection for armv6l

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#235]
It seems people still want to use the gem on Raspberry Pis. Add `armv6` arch detection despite it taking days to compile and me being unable to produce binaries for it.

https://github.com/cowboyd/libv8/issues/234

**Comment by hipcrime** [comment]
Don't really want to use this Gem but want to use Beef which requires it.  That being said, more than happy to let one of my many Pis run for however many days it takes to get a valid compilation.  Would also happily share the binaries, if you wanted them.

**Comment by ignisf** [comment]
Thank you for your offer, however due to security concerns I cannot really take it up 😟. I've raised an issue with the Beef team with a suggestion how to resolve the necessity to depend on therubyracer.
