### ISSUE TITLE
No binary for manually compiled ruby on FreeBSD 11 amd64

### ISSUE THREAD

**Issue by nanaya** [cowboyd/libv8#238]
On FreeBSD 11.

I'm not sure which part is at fault here but manually compiling ruby using either plain `./configure <options> && make && make install` or default `ruby-install` will result in `RbConfig::CONFIG['arch'] => x86_64-freebsd11` which doesn't have precompiled binary because there's only `amd64-freebsd-11`.

FWIW, for FreeBSD 10 there are both `x86_64` and `amd64`. And installing ruby via `pkg` also results in `amd64-freebsd11`.

On unrelated note, manual build of the gem doesn't work (failed at `gclient sync` for some reason).

**Comment by ignisf** [comment]
Hello @nanaya,

Thank you very much for the report! We hit this issue once already with a Ruby installed through RVM. https://github.com/cowboyd/libv8/issues/236 https://github.com/rvm/rvm/issues/4037.

This gives me a lead where to look for this inconsistent behaviour. Will also take a look at the `gclient sync` issue.

(Also, what's with the anime avatars throughout github, is it a joke I'm not in on or do people just like anime?)

**Comment by nanaya** [comment]
Whoops, I just find out the related issue as well (unrelated title didn't help).

From what I can track, ports system [set (or something)](https://svnweb.freebsd.org/ports/head/Mk/bsd.ruby.mk?revision=439972&view=markup#l225) `RUBY_ARCH` to `amd64` (and perhaps some more stuff), hence different triplet.

Additionally, `autoconf` specifically modifies `amd64` to `x86_64` (probably to unify the names?). So, yeah, I'm confused.

I noticed [some](https://svnweb.freebsd.org/ports/head/multimedia/xvid/Makefile?revision=434587&view=markup#l37) [ports](https://svnweb.freebsd.org/ports/head/devel/libbfd/Makefile?revision=434587&view=markup#l25) override it to make it `x86_64` instead so I guess it's the ports' ruby being incorrect?

(I think people just like anime)

**Comment by ignisf** [comment]
Haven't taken a look yet, but you more or less did what I was planning to do. I'll confirm later but it seems we have a few ways of going forward: 

* submit patches to Ruby that make behaviour consistent on FreeBSD
* submit patches to FreeBSD to make sure its ports system does not interfere with Ruby's build
* start releasing both an amd64-* and an x86_64-* versions for FreeBSD

**Comment by ignisf** [comment]
I like better the first two options, not sure which is more correct at this point.

**Comment by ignisf** [comment]
I've added build scripts that use RVM and produce x86_64* gems.
