### ISSUE TITLE
compile fails on high sierra

### ISSUE THREAD

**Issue by selfagency** [cowboyd/libv8#239]
libv8 appears to cause the failure of homebrew packages of which it is a dependency to compile under mac os high sierra (dev beta 2).

```
==> Downloading https://download.rethinkdb.com/dist/rethinkdb-2.3.5.tgz
Already downloaded: /Users/daniel/Library/Caches/Homebrew/rethinkdb-2.3.5.tgz
==> Downloading https://github.com/rethinkdb/rethinkdb/pull/6024.patch?full_index=1
Already downloaded: /Users/daniel/Library/Caches/Homebrew/rethinkdb--patch-cc8d8cae6e266cc0e417a844d0103b817caadc8e634e46e6bf50b778ce676377.patch
==> Patching
==> Applying 6024.patch
patching file src/clustering/administration/main/cache_size.cc
==> ./configure --prefix=/usr/local/Cellar/rethinkdb/2.3.5 --fetch protobuf
==> make
Last 15 lines from /Users/daniel/Library/Logs/Homebrew/rethinkdb/02.make:
make[3]: *** [/private/tmp/rethinkdb-20170703-74108-68cxnq/rethinkdb-2.3.5/build/external/v8_3.30.33.16/build/out/x64.release/obj.target/v8_base/src/assert-scope.o] Error 1
1 error generated.
make[3]: *** [/private/tmp/rethinkdb-20170703-74108-68cxnq/rethinkdb-2.3.5/build/external/v8_3.30.33.16/build/out/x64.release/obj.target/v8_base/src/accessors.o] Error 1
1 error generated.
make[3]: *** [/private/tmp/rethinkdb-20170703-74108-68cxnq/rethinkdb-2.3.5/build/external/v8_3.30.33.16/build/out/x64.release/obj.target/v8_base/src/assembler.o] Error 1
1 error generated.
make[3]: *** [/private/tmp/rethinkdb-20170703-74108-68cxnq/rethinkdb-2.3.5/build/external/v8_3.30.33.16/build/out/x64.release/obj.target/v8_base/src/ast.o] Error 1
1 error generated.
make[3]: *** [/private/tmp/rethinkdb-20170703-74108-68cxnq/rethinkdb-2.3.5/build/external/v8_3.30.33.16/build/out/x64.release/obj.target/v8_base/src/api.o] Error 1
make[2]: *** [x64.release] Error 2

Full error log: ./build/external/v8_3.30.33.16_install.log
make[1]: *** [build/external/v8_3.30.33.16/lib/libv8.a] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [make] Error 2
```

**Comment by ignisf** [comment]
Hya,

Are you sure rethinkdb uses the libv8 *ruby gem* and not directly the *V8 library* from Google?

**Comment by selfagency** [comment]
it's possible but node is installing just fine which also uses the v8 library.

**Comment by ignisf** [comment]
I took a closer look.

Unfortunately rethinkdb does in fact fetch a patched version of the V8 library (v8_3.30.33.16-patched) and embeds it. It's also quite an ancient version which is probably why it fails on your brand new system.

I don't think that has anything to do with this Rubygem, so I'm going to close the issue.

**Comment by selfagency** [comment]
Ok thanks and sorry for the false report

**Comment by ignisf** [comment]
No worries :)

**Comment by Fjan** [comment]
I can't get the libv8 gem to install on a clean High Sierra install. It does not give any error, it just keeps compiling indefinitely. I tired older versions of the gem too, without any luck. Anybody managed to install this gem on High Sierra? Should I open another issue?

**Comment by ignisf** [comment]
Hello, please open a new issue, thanks :)

**Comment by mhassaan** [comment]
@Fjan I have just finished installing '3.16.14.11' version of libv8 gem on a clean High Sierra. This version works fine. The command that worked for me is `gem install libv8 -v '3.16.14.11' -- --with-system-v8`. Hope that helps.
