### ISSUE TITLE
New release with 5.9

### ISSUE THREAD

**Issue by SamSaffron** [cowboyd/libv8#240]
5.9 of v8 was recently release and has some really cool perf fixes. 

I would love to get it to become stable of of libv8 as soon as we can.

**Comment by krzysiek1507** [comment]
There is also 6.0 released

**Comment by SamSaffron** [comment]
I think 6.0 is the beta stream, chrome stable is on 59

**Comment by ignisf** [comment]
Working on 5.9 in https://github.com/cowboyd/libv8/tree/5.9

**Comment by ignisf** [comment]
Had to backport https://chromium-review.googlesource.com/c/530227/

**Comment by ignisf** [comment]
beta binaries are compiling cc @seanmakesgames

**Comment by ignisf** [comment]
The beta binaries are up on Rubygems. I think we should be fine for release though.

**Comment by seanmakesgames** [comment]
@SamSaffron @ignisf getting a handful of 
`mini_racer.rb:168: warning: instance variable @disposed not initialized`
for every mini_racer test when it's run. All i've done is 
`spec.add_dependency 'libv8', '5.9.211.38.0beta0'`
with mini_racer master.
I'm not sure if this is a libv8 issue or a mini_racer issue, as the errors don't come up when using the earlier version of libv8. (also this comment may belong on mini_racer's issue list, just lmk where you want to have this discussion)

:)

**Comment by SamSaffron** [comment]
OK the warnings are unrelated, I just pushed a fix, you were probably
running with RUBYOPT=-W2 somehow

@ignisf I say push this out by the end of the week :) :)

**Comment by seanmakesgames** [comment]
verified & confirmed @SamSaffron 
pointed my tests at the beta binaries, running them now. @ignisf

**Comment by seanmakesgames** [comment]
Tests look good.

**Comment by ignisf** [comment]
👏👏👏

I'm on it

**Comment by ignisf** [comment]
done.
