### ISSUE TITLE
Kotlin complains about missing ArrayBuffer

### ISSUE THREAD

**Issue by sleekweasel** [cowboyd/libv8#242]
I'm trying to run Kotlin under rubyracer, but whereas my Chrome browser - running the same V8 5.9.211.38 - successfully loads kotlin.js and test.js to print 'Hello World' in the console, RubyRacer reports missing ArrayBuffer, when I try to load the 'kotlin.js' file:

Updating files in vendor/cache
  * libv8-5.9.211.38.0beta0-x86_64-darwin-14.gem
Removing outdated .gem files from vendor/cache
  * libv8-5.7.492.65.1-x86_64-darwin-14.gem
Bundle complete! 32 Gemfile dependencies, 132 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
[10:12:11]~/git/bma-calabash (CAL-2855_Try_JRuby)$ bundle exec irb
2.1.5 :001 > require 'v8'
 => true 
2.1.5 :002 > V8::Context.new.load('kotlib/kotlin.js')
V8::Error: ArrayBuffer is not defined
        from at kotlib/kotlin.js:790:12
        from at kotlib/kotlin.js:10:9

I can't tell whether ArrayBuffer is missing from the libv8 gem, or Ruby Racer can't access it for some reason.

**Comment by sleekweasel** [comment]
Actually, it looks like this is a racer issue: someone suggested I try with mini_racer, and that doesn't complain about ArrayBuffer with whatever v8 it's picking up.

**Comment by ignisf** [comment]
>.>
