### ISSUE TITLE
With install Ruby 2.4.3 (and 2.3.6, 2.5.0) and Passenger 5.1.12 ALL sites will fail to open

### ISSUE THREAD

**Issue by Sega100500** [cowboyd/libv8#254]
With install **Ruby 2.4.3** (and **2.3.6**, **2.5.0**) and **Passenger 5.1.12** ALL sites will fail to open:

**Incomplete response received from application**

from git of Passenger point to problem: https://github.com/phusion/passenger/issues/2010

in log-file exists ```v8``` :

```
App 21106 stderr: 
  /home/ruby/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/context.rb:99: [BUG] Segmentation fault at 0x0000000000000000
App 21106 stderr: ruby 2.4.3p205 (2017-12-14 revision 61247) 
...
App 21106 stderr: [NOTE]
App 21106 stderr: You may have encountered a bug in the Ruby interpreter or extension libraries.
App 21106 stderr: Bug reports are welcome.
App 21106 stderr: For details: http://www.ruby-lang.org/bugreport.html
```

**/home/ruby/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/context.rb:99**

Without ```gem 'therubyracer', platforms: :ruby``` in Gemfile no one application not working (even in development mode - without Apache+Passenger - ```rails -s```)!

_May by in your library a problem?_

full-debug Apache Passanger file:
[passenger.log.debug-7.log](https://github.com/cowboyd/libv8/files/1588403/passenger.log.debug-7.log)

**Comment by Sega100500** [comment]
I wrote to the ```therubyracer``` :  https://github.com/cowboyd/therubyracer/issues/444
But this gem possible die? (Latest commit 466a1f0  on 5 Jan)

**Comment by Sega100500** [comment]
full-debug log-file
[passenger.log.debug-7.log](https://github.com/cowboyd/libv8/files/1588402/passenger.log.debug-7.log)

**Comment by Sega100500** [comment]
more debug info
[passenger.level7.log.therubyracer.bug.log](https://github.com/cowboyd/libv8/files/1588574/passenger.level7.log.therubyracer.bug.log)

**Comment by ignisf** [comment]
Hello @Sega100500,

It's bad etiquette to open multiple tickets in multiple projects for the same issue.

**Comment by Sega100500** [comment]
Hello @ignisf 

I do it not for malicious intent. Simply in each of the components of the system they answer me: "This is not our fault, our system has nothing to do with it, everything works for us," and then they close the topic.

And PROBLEM exists!!!

**Comment by paulomcnally** [comment]
On heroku have a 404 error trying download: https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.1.12/rubyext-ruby-2.4.3-x86_64-linux.tar.gz
