### ISSUE TITLE
V8 6.3 exposes its users to the Meltdown and Spectre attacks if used for executing untrusted code

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#255]
As far as I understand, the following conditions need to be met:
1. You have to be using V8 to run untrusted code.
2. You have to be running V8 on an unpatched OS.

Mitigations have been merged in 6.4 beta, see:

* https://github.com/v8/v8/commit/a060a4fc565aa40fcb3acb6b075936b78b38fc10
* https://chromium-review.googlesource.com/c/v8/v8/+/848921
* https://sites.google.com/a/chromium.org/dev/Home/chromium-security/ssca

* https://googleprojectzero.blogspot.bg/2018/01/reading-privileged-memory-with-side.html
* https://spectreattack.com/
* https://meltdownattack.com/

**Comment by ignisf** [comment]
@seanmakesgames, @samsaffron ^

**Comment by seanmakesgames** [comment]
whoops all I use v8 for is executing untrusted code -- @ignisf is this a 6.3 and below or a 6.3 bug?

**Comment by ignisf** [comment]
looking at the patches, it relies on wasm... so I suspect it's since wasm was introduced. :/

**Comment by seanmakesgames** [comment]
Excellent. I don't support wasm, so as long as I keep that layer secure things are harder. I have a group of players trying to break it as well, they have some concerns with getting it to work in js, so we'll see how it goes. :)

**Comment by SamSaffron** [comment]
Yeah let's keep this open till 6.4 is released, but the vuls have been in place for a very long time. 

Keep in mind that OS patches will also "fix" this without a 6.4 upgrade and long term a CPU upgrade will fix this as well.

**Comment by YurySolovyov** [comment]
[V8 6.7 is out by now](https://v8project.blogspot.com/2018/05/v8-release-v67.html) with Untrusted code mitigations
