### ISSUE TITLE
Add aarch64 support to libv8 3.16

### ISSUE THREAD

**Issue by Hax4us** [cowboyd/libv8#257]

**Comment by ignisf** [comment]
Hya,

FYI, there's a binary for aarch64: https://rubygems.org/gems/libv8/versions/6.3.292.48.1-aarch64-linux

What issue are you experiencing with the support?

**Comment by Hax4us** [comment]
Installed but i m unable to install rubyracer with this libv8

**Comment by Hax4us** [comment]
ok so we have aarch64 support but why rubyracer is not installing ? I m closing this issue and going to open new issue in your rubyracer repo with mkmf.log details

**Comment by ignisf** [comment]
Ah, I see your issue now. Unfortunately the version of libv8 therubyracer requires does not have upstream aarch64 support :/. It's pretty ancient and at this point it's unfeasible to add it. I'd suggest you migrate to `mini_racer` instead if possible. It links against the current version of libv8

**Comment by Hax4us** [comment]
Oh shitt...actually i want rubyracer for most popular tool *BeeF* :( kk i will wait for rubyracer

**Comment by ignisf** [comment]
https://github.com/beefproject/beef/issues/1374

**Comment by Hax4us** [comment]
:) Thnx dude
