### ISSUE TITLE
undefined symbol: _ZNKSt3__119__shared_weak_count13__get_deleterERKSt9type_info when requiring gem linked against libv8 7.0

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#274]
We probably have a conflict due to the use of a custom libcxx by V8's build system.

```
/home/ignisf/Projects/mini_racer/lib/mini_racer.rb:2:in `require': /home/ignisf/Projects/mini_racer/lib/mini_racer_extension.so: undefined symbol: _ZNKSt3__119__shared_weak_count13__get_deleterERKSt9type_info - /home/ignisf/Projects/mini_racer/lib/mini_racer_extension.so (LoadError)
```

Relevant links:

https://reviews.llvm.org/file/data/ckl3iejghvcctzsyxpap/PHID-FILE-gj2uveqtrt3misqrrqht/file

**Comment by ignisf** [comment]
The issue was due to the use of the custom libc++ library V8 for gets shipped with for some reason.

**Comment by sriemer** [comment]
I had the same issue with my library linked statically against `libc++` with LLVM 13. The `lld-13` linker is required to fix this in my case. I use the linker flags `-pthread -static-libgcc -ldl -fuse-ld=lld-13 -Wl,--version-script=${PWD}/export.map -nostdlib++ /usr/lib/llvm-13/lib/libc++.a /usr/lib/llvm-13/lib/libc++abi.a` now.
Maybe this helps someone else finding this issue via web search as well.
