### ISSUE TITLE
missing libv8-6.7.288.46.1.gem in release assets?

### ISSUE THREAD

**Issue by alexagranov** [cowboyd/libv8#276]
Not seeing that gem in assets for https://github.com/cowboyd/libv8/releases/tag/v6.7.288.46.1 and bundler now complaining:

```
Step 53/65 : RUN bundle install --deployment --without test development
 ---> Running in 1d99340606b7
Some gems seem to be missing from your vendor/cache directory.
Could not find libv8-6.7.288.46.1 in any of the sources
```

I see there is a non-OS specific gem for other releases though.

**Comment by ignisf** [comment]
Github has deleted it for some reason? It asked me to reupload

**Comment by alexagranov** [comment]
thanks @ignisf !
