### ISSUE TITLE
Upgrading to v8 7.3

### ISSUE THREAD

**Issue by SamSaffron** [cowboyd/libv8#277]
Howdy @ignisf  appears we are quite behind on v8. Current version is 7.3. 

Any chance we can look at an upgrade? Anything I can do to help?

**Comment by ignisf** [comment]
Hi,
I have to get this sorted https://github.com/discourse/mini_racer/pull/117 as a start

There seem to be a few more incompatibilities that I have to check more closely

**Comment by ignisf** [comment]
The few more incompatibilities are being tracked here: https://github.com/discourse/mini_racer/issues/115

**Comment by ignisf** [comment]
The new version has been pushed to Rubygems
