### ISSUE TITLE
libv8 on Windows

### ISSUE THREAD

**Issue by yagmurdursun** [cowboyd/libv8#29]
I work on Windows and I developed an application. It was working but after installed a gem (twitter-bootstrap-rails) I started to get "Python not found." What can I do about it?

   Installing libv8 (3.3.10.4) with native extensions
   Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

   c:/Ruby192/bin/ruby.exe extconf.rb
   **\* extconf.rb failed ***
   Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.
   Check the mkmf.log file for more details. You may need configuration options.

   Provided configuration options:
   --with-opt-dir
   --without-opt-dir
   --with-opt-include
   --without-opt-include=${opt-dir}/include
   --with-opt-lib
   --without-opt-lib=${opt-dir}/lib
   --with-make-prog
   --without-make-prog
   --srcdir=.
   --curdir
   --ruby=c:/Ruby192/bin/ruby
   Checking for Python...Unable to build libv8: Python not found!

**Comment by badbob** [comment]
This error is about a libv8-3.11.8.17\ext\libv8\builder.rb script. 
On line 60 we can see this code:
```
`python -c 'import platform; print(platform.python_version())'`.chomp
```

This is a wrond python command syntax in Windows. You should use a double quotes, like this:
```
`python -c "import platform; print(platform.python_version())"`.chomp
```

After fixing this script, you should run gem install with "-l" (use local only) key. If you don't, gem will download a script with an error again.

**Comment by mnuzzolilo** [comment]
@badbob 
```
C:\Users\Admin>gem install libv8 -l
ERROR:  Could not find a valid gem 'libv8' (>= 0) in any repository
```
