### ISSUE TITLE
Missing macOS Monterey build (x86_64-darwin-21)

### ISSUE THREAD

**Issue by ksylvest** [cowboyd/libv8#318]
It looks like as part of Monterey the platform changed to `x86_64-darwin-21`. The installation currently works via: `gem install libv8 --platform="x86_64-darwin-20"` on Monterey.

Looks like this again: https://github.com/rubyjs/libv8/issues/305

**Comment by tushar-innovalabs** [comment]
Having same error while `bundle install` on rails. Can you please help how to do using `bundle install` ?

**Comment by odedltr** [comment]
I need libv8 as a dependency for `mini_racer`. 
Tried also to run `gem install libv8 -v '7.3.492.27.1' --source 'https://rubygems.org/'`, fails after ~20 mins



```
ERROR:  Error installing libv8:
ERROR: Failed to build gem native extension.

IOError: [Errno 2] No such file or directory: '/.rvm/gems/ruby-2.5.3@elocal_call_center/gems/libv8-7.3.492.27.1/vendor/build/config/gclient_args.gni'
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Subprocess failed with return code 1.
/.rvm/gems/ruby-2.5.3@elocal_call_center/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:83:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /rvm/gems/ruby-2.5.3@elocal_call_center/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `chdir'
	from /.rvm/gems/ruby-2.5.3@elocal_call_center/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `setup_build_deps!'
	from /.rvm/gems/ruby-2.5.3@elocal_call_center/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:40:in `build_libv8!'
	from /.rvm/gems/ruby-2.5.3@elocal_call_center/gems/libv8-7.3.492.27.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1
```

**Comment by ksylvest** [comment]
This works as a workaround (modified from the other issue lloek identified):

```sh
#!/bin/bash
# filename: gem-install-libv8-darwin-20.sh

set -e
set -u
set -o pipefail

libv8_version="${1:-"8.4.255.0"}"
from='20'
to='21'

gem_home="$(ruby -e 'puts Gem.dir')"
ruby_platform="$(ruby -e 'puts Gem.platforms.select { |p| Gem::Platform === p && p.os =~ /darwin/ }')"
ruby_platform_prefix="${ruby_platform%-*}"

# case "${ruby_platform}" in
#     *universal*)
#         ruby_platform_prefix="x86_64-darwin"
#         ;;
# esac

ruby_platform_from="${ruby_platform_prefix}-${from}"
ruby_platform_to="${ruby_platform_prefix}-${to}"

echo " *** detecting"

echo "${gem_home}"
echo "${ruby_platform}"
echo "${ruby_platform_prefix}"

echo "libv8 ${libv8_version}: ${ruby_platform_from} => ${ruby_platform_to}"

echo " *** downloading"

test -f "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem" \
    || curl --fail --output "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem" "https://rubygems.org/downloads/libv8-${libv8_version}-${ruby_platform_from}.gem" \
    || curl --fail --output "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem" "https://rubygems.org/downloads/libv8-${libv8_version}-${ruby_platform_prefix}${from}.gem"

echo " *** cleaning"

rm -rfv "${gem_home}/specifications/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gemspec"
rm -rfv "${gem_home}/doc/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
rm -rfv "${gem_home}/gems/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
rm -rfv "${gem_home}/cache/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gem"

echo " *** installing"

gem install "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem"

echo " *** patching"

mv -v "${gem_home}/specifications/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gemspec"
mv -v "${gem_home}/doc/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
mv -v "${gem_home}/gems/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
mv -v "${gem_home}/cache/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gem"

sed -i~ \
    -e "s/${ruby_platform_prefix}-${from}/${ruby_platform_to}/" \
    -e "s/${ruby_platform_prefix}${from}/${ruby_platform_to}/" \
    "${gem_home}/specifications/libv8-${libv8_version}-${ruby_platform_to}.gemspec"
rm "${gem_home}/specifications/libv8-${libv8_version}-${ruby_platform_to}.gemspec~"

echo " *** result"

find "${gem_home}"/*/"libv8-${libv8_version}-${ruby_platform_to}"
grep --text "${ruby_platform_to}" "${gem_home}/specifications/libv8-${libv8_version}-${ruby_platform_to}.gemspec"

```

**Comment by sethpalmer** [comment]
> @ksylvest thank you for this. How you suggest this should be used? Ran it from my project and it seems that bundler is using it. However if you have a GEM that needs `libv8`, bundler complains that there is a missing dependency.
> 
> ```
> Using libv8 8.4.255.0 (x86_64-darwin-21)
> .
> .
> .
> Downloading mini_racer-0.2.6 revealed dependencies not in the API or the lockfile (libv8 (>= 6.9.411)).
> Either installing with `--full-index` or running `bundle update mini_racer` should fix the problem.
> ```
> 
> (`--full-index` or running `bundle update mini_racer` don't help)

Also running into this issue

**Comment by bernardo-martinez** [comment]
> ```shell
> gem-install-libv8-darwin-20.sh
> ```

using this and looks like its installed correctly:
```
*** installing
Successfully installed libv8-7.3.492.27.1-x86_64-darwin-20
Parsing documentation for libv8-7.3.492.27.1-x86_64-darwin-20
Installing ri documentation for libv8-7.3.492.27.1-x86_64-darwin-20
Done installing documentation for libv8 after 0 seconds
1 gem installed
 *** patching
 ...
 ```

 but then running: `gem query --local | grep libv8` is empty

**Comment by okarny** [comment]
are you going to be adding an install for x86_64-darwin-21?

**Comment by karthikbp21** [comment]
Facing issue 
An error occurred while installing libv8 (7.3.492.27.1), and Bundler cannot continue.
Make sure that `gem install libv8 -v '7.3.492.27.1'` succeeds before bundling.

Current 0S Monterey (x86_64-darwin-21)

Please help me to run bundle on my project

**Comment by OmriSama** [comment]
> are you going to be adding an install for x86_64-darwin-21?

bump

**Comment by paulomcnally** [comment]
This work:

```
gem install libv8 -v '7.3.492.27.1' --platform="x86_64-darwin-20"

```

**Comment by TaheerMattur** [comment]
Is there anyway to install libv8 in Mac -Monterey (x86_64-darwin-21)?? Tried every method..
And @ksylvest How to use this binary method ??
#!/bin/bash
# filename: gem-install-libv8-darwin-20.sh ??????????

**Comment by estraph** [comment]
Hi all - this issue has become a blocker for me and my team and I wonder if there's anything I can to help?

We're unable to `bundle install` `mini_racer` 0.3.1 because it still depends on `libv8` 8.4.255.0 which fails to buid:

```
________ running 'vpython third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/vendor'
/Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/vendor/depot_tools/.cipd_bin/vpython: could not resolve options: failed to resolve Python script: stat
/Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/vendor/third_party/depot_tools/update_depot_tools_toggle.py: no such file or directory
Error: Command 'vpython third_party/depot_tools/update_depot_tools_toggle.py --disable' returned non-zero exit status 1 in
/Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/vendor
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Subprocess failed with return code 2.
/Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:83:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:81:in `chdir'
	from /Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:81:in `setup_build_deps!'
	from /Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:40:in `build_libv8!'
	from /Users/foo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-8.4.255.0/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1
```

 Upgrading `mini_racer` fixes the `bundle install` issue, but the newer version of `mini_racer` also bumps the `node` version which is a problem for us. Using `--with-system-v8` didn't work. Installing directly with `gem install ... --platform=` (using `darwin-20`) installs on its own but doesn't prevent `bundler` from hitting the problem again. Upgrading `bundler` and using `--add-platform` didn't work.

Starting to run out of ideas here 😅

**Comment by estraph** [comment]
It seems like the [script provided by @ksylvest](https://github.com/rubyjs/libv8/issues/318#issuecomment-956466977) got it installed - are there any plans to solve this in a better fashion?

**Comment by bensaufley** [comment]
For whatever it's worth, nothing in this thread worked for me. I ended up upgrading `mini_racer` (which had `libv8` as a dependency) and `mini_racer` has switched to `libv8-node`, which works for me on an M1 MacBook with Monterrey.

**Comment by OmriSama** [comment]
> For whatever it's worth, nothing in this thread worked for me. I ended up upgrading `mini_racer` (which had `libv8` as a dependency) and `mini_racer` has switched to `libv8-node`, which works for me on an M1 MacBook with Monterrey.

Yeah pretty much. Using `libv8-node` is now the recommended thing. lol

**Comment by vlado** [comment]
After running the [script](https://github.com/rubyjs/libv8/issues/318#issuecomment-956466977) from @ksylvest I had to manually add `libv8 (8.4.255.0-x86_64-darwin-21)` to my Gemfile.lock for `bundle install` to pass.

```
# Gemfile.lock
...
letter_opener (1.7.0)
      launchy (~> 2.2)
libv8 (8.4.255.0)
libv8 (8.4.255.0-x86_64-darwin-20)
libv8 (8.4.255.0-x86_64-darwin-21)
libv8 (8.4.255.0-x86_64-linux)
listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
...
```

I also had to remove `mv -v "${gem_home}/doc/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}` line cause I have `gem: "--no-document"` in my `.gemrc`.

**Comment by jrob00** [comment]
I'm supporting a legacy app running:
- Ventura 13.1 (x86_64-darwin-22)
- ruby 2.3.8 with rvm
- rails 4.2.7.1

It looks like this thread won't help synthetic core users but I'm still on intel and the `gem-install-libv8-darwin-20.sh `script @ksylvest shared worked for me.

After that I ran `bundle install` which worked without needing to modify `Gemfile.lock` as someone stated above.

Thanks @ksylvest and @lloeki for your efforts.
