### ISSUE TITLE
ARM architecture detection is unreliable 

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#98]
We need to be able to reliably determine when the source version of the gem is being installed on an arm system and _if the arm system uses a hard-float ABI_.

Currently we don't have the necessary hardware to test, so we would be grateful if anybody (@cpg, @glennmartinez, @lunij, @Lyann, @clark800) could provide the output of the Ruby source below for the specified distros.

``` ruby
require 'pp'
PP.pp RbConfig::CONFIG
puts RUBY_VERSION, RUBY_PLATFORM, `uname -a`
```
- [ ] Raspbian Wheezy Soft-float (on the Raspberry Pi)
- [x] Raspbian Wheezy Hard-float (on the Raspberry Pi)
- [x] archlinux-hf (on the Raspberry Pi)
- [x] Pidora (on the Raspberry Pi)
- [x] FreeBSD arm (on any of the supported platforms, especially the Raspberry Pi)
- [x] Ubuntu Linaro (on any of the supported platforms, especially the Cubie Board)
- [ ] Any other ARM distro

**Comment by noloader** [comment]
@ignisf,

> Just committed initial support for 64-bit ARM CPUs that also needs testing...

Robert Nelson has an early Mustang server board. Its unique in that its Aarch64/ARMv8, but it lacks CRC and Crypto extensions. He provides SSH access to it for those who desire it. You can reach him at *robertcnelson, gmail account*.

If you need some inexpensive Aarch64 dev-boards, then try either:

* [LeMaker HiKey](http://www.amazon.com/dp/B019O3QTSA), $169 USD
* [DragonBoard 410C](http://developer.qualcomm.com/hardware/dragonboard-410c), $79 USD
